from __future__ import annotations

from pathlib import Path
from typing import Any

from fastapi import FastAPI, HTTPException, Request
from fastapi.responses import FileResponse
from fastapi.staticfiles import StaticFiles
from pydantic import BaseModel, Field

from dev_orchestrator.config import AppConfig, update_config
from dev_orchestrator.llm_client import OpenAICompatibleClient, list_provider_profiles
from dev_orchestrator.llm_contract_check import run_llm_contract_check
from dev_orchestrator.v5.llm_policy import list_ai_task_budgets
from dev_orchestrator.v5.models import DEFAULT_TENANT, new_id
from dev_orchestrator.v5.service import DeliveryExportError, ProjectPathError, V5Orchestrator
from dev_orchestrator.v5.system_check import build_v5_system_check
from dev_orchestrator.v5.worker import WorkerStatusRegistry


class ProjectCreate(BaseModel):
    name: str = ""
    title: str = ""
    description: str = ""
    target_scale: str = "small"
    stack_pack: str = "auto"
    deployment_mode: str = ""
    api_only: bool = False
    effective_loc_target: int = 1000
    unattended_mode: str = "off"
    project_path: str = ""
    config: dict[str, Any] = Field(default_factory=dict)


class RequirementUpdate(BaseModel):
    requirements_text: str


class RunCreate(BaseModel):
    requirements_text: str = ""


class ProjectBatchDelete(BaseModel):
    project_ids: list[str] = Field(default_factory=list)


class DeliveryExportRequest(BaseModel):
    target_path: str = ""
    overwrite: bool = False


class ModelSettingsUpdate(BaseModel):
    llm: dict[str, Any] = Field(default_factory=dict)
    model_provider: str = ""
    model_providers: dict[str, Any] = Field(default_factory=dict)
    model: str = ""
    model_reasoning_effort: str = ""
    disable_response_storage: bool | None = None
    api_key: str = ""


RECOMMENDED_CUSTOM_MODEL_SETTINGS: dict[str, Any] = {
    "model_provider": "custom",
    "model": "gpt-5.3-codex",
    "model_reasoning_effort": "xhigh",
    "disable_response_storage": True,
    "model_providers": {
        "custom": {
            "name": "custom",
            "wire_api": "responses",
            "requires_openai_auth": True,
            "base_url": "https://deepkey.top/v1",
        }
    },
}


def build_app(service: V5Orchestrator, config: AppConfig) -> FastAPI:
    app = FastAPI(title="Dev Orchestrator V5", version="5.0")
    static_root = config.root_dir / "dev_orchestrator" / "static"
    if static_root.exists():
        app.mount("/static", StaticFiles(directory=str(static_root)), name="static")

    @app.get("/")
    def index():
        index_path = static_root / "index.html"
        if index_path.exists():
            return FileResponse(index_path)
        return {"service": "dev-orchestrator-v5", "api": "/api/v5/health"}

    @app.get("/api/v5/health")
    def health() -> dict[str, Any]:
        return {"status": "ok", "kernel": "v5", "storage": "postgres", "tenant": service.tenant_id}

    @app.get("/api/v5/system-check")
    def system_check() -> dict[str, Any]:
        return build_v5_system_check(config.root_dir, config.to_dict(), strict_db=False)

    @app.get("/api/v5/stack-packs")
    def stack_packs() -> dict[str, Any]:
        return {"items": [], "policy": "stack packs are AI guidance only; project structure and files are generated by agents"}

    @app.get("/api/v5/ai-policy")
    def ai_policy() -> dict[str, Any]:
        return {
            "policy": "ai-agent-native-file-manifest",
            "principles": [
                "Project layout, source files, tests, docs, and release notes are generated by AI agents.",
                "The system validates and applies file-manifest patches but does not render product code.",
                "Every agent call has explicit input, output, timeout, reasoning, and retry budgets.",
            ],
            "budgets": list_ai_task_budgets(),
        }

    @app.get("/api/v5/model-settings")
    def get_model_settings() -> dict[str, Any]:
        return {
            "llm": config.to_dict()["llm"],
            "provider_profiles": list_provider_profiles(),
            "recommended": RECOMMENDED_CUSTOM_MODEL_SETTINGS,
        }

    @app.put("/api/v5/model-settings")
    def update_model_settings(payload: ModelSettingsUpdate) -> dict[str, Any]:
        llm_payload = _normalize_model_settings_payload(payload.model_dump())
        updated = update_config(config, {"llm": llm_payload})
        _sync_llm_env_file(config.root_dir, updated.llm)
        service.update_llm_client(OpenAICompatibleClient(updated.llm))
        return {
            "ok": True,
            "llm": updated.to_dict()["llm"],
            "provider_profiles": list_provider_profiles(),
            "recommended": RECOMMENDED_CUSTOM_MODEL_SETTINGS,
        }

    @app.post("/api/v5/model-settings/test")
    def test_model_settings(payload: ModelSettingsUpdate) -> dict[str, Any]:
        llm_payload = _normalize_model_settings_payload(payload.model_dump())
        probe_config = update_config(config, {"llm": llm_payload})
        _sync_llm_env_file(config.root_dir, probe_config.llm)
        service.update_llm_client(OpenAICompatibleClient(probe_config.llm))
        result = run_llm_contract_check(service.llm_client)
        return {
            "ok": bool(result.get("ok")),
            "result": result,
            "llm": probe_config.to_dict()["llm"],
            "provider_profiles": list_provider_profiles(),
            "recommended": RECOMMENDED_CUSTOM_MODEL_SETTINGS,
        }

    @app.post("/api/v5/projects")
    def create_project(payload: ProjectCreate, request: Request) -> dict[str, Any]:
        tenant_id = request.headers.get(config.identity.tenant_header) or service.tenant_id
        data = payload.model_dump()
        config_payload = dict(data.pop("config") or {})
        for key in ("target_scale", "stack_pack", "deployment_mode", "api_only", "effective_loc_target", "unattended_mode"):
            config_payload[key] = data.pop(key)
        data["config"] = config_payload
        try:
            project = service.create_project(data, tenant_id=tenant_id)
        except ProjectPathError as exc:
            raise HTTPException(status_code=400, detail=str(exc))
        return {"project": project}

    @app.get("/api/v5/projects")
    def list_projects(request: Request) -> dict[str, Any]:
        tenant_id = request.headers.get(config.identity.tenant_header) or service.tenant_id
        return {"items": service.list_projects(tenant_id)}

    @app.get("/api/v5/projects/{project_id}")
    def get_project(project_id: str) -> dict[str, Any]:
        project = service.get_project(project_id)
        if not project:
            raise HTTPException(status_code=404, detail="project not found")
        return {"project": project}

    @app.get("/api/v5/projects/{project_id}/runs")
    def list_project_runs(project_id: str) -> dict[str, Any]:
        project = service.get_project(project_id)
        if not project:
            raise HTTPException(status_code=404, detail="project not found")
        return {"items": service.list_runs(project_id)}

    @app.delete("/api/v5/projects/{project_id}")
    def delete_project(project_id: str) -> dict[str, Any]:
        project = service.get_project(project_id)
        if not project:
            raise HTTPException(status_code=404, detail="project not found")
        return {"ok": True, "result": service.store.delete_project(project_id)}

    @app.post("/api/v5/projects/batch-delete")
    def batch_delete_projects(payload: ProjectBatchDelete) -> dict[str, Any]:
        if not payload.project_ids:
            raise HTTPException(status_code=400, detail="project_ids is required")
        return {"ok": True, "result": service.store.delete_projects(payload.project_ids)}

    @app.post("/api/v5/projects/{project_id}/requirements")
    def update_requirements(project_id: str, payload: RequirementUpdate) -> dict[str, Any]:
        project = service.get_project(project_id)
        if not project:
            raise HTTPException(status_code=404, detail="project not found")
        service.store.add_event(project["tenant_id"], project_id, None, "requirements_updated", {"requirements_text": payload.requirements_text})
        return {"ok": True, "project_id": project_id}

    @app.get("/api/v5/projects/{project_id}/stack-decision")
    def stack_decision(project_id: str) -> dict[str, Any]:
        project = service.get_project(project_id)
        if not project:
            raise HTTPException(status_code=404, detail="project not found")
        return {"project_id": project_id, "decision": {"ok": True, "mode": "ai_agent_native", "reason": "architecture_agent decides project layout and technology structure"}}

    @app.post("/api/v5/projects/{project_id}/runs")
    def create_run(project_id: str, payload: RunCreate) -> dict[str, Any]:
        project = service.get_project(project_id)
        if not project:
            raise HTTPException(status_code=404, detail="project not found")
        try:
            run = service.create_run(project_id, payload.requirements_text)
        except ProjectPathError as exc:
            raise HTTPException(status_code=400, detail=str(exc))
        return {"run": run}

    @app.get("/api/v5/runs/{run_id}")
    def get_run(run_id: str) -> dict[str, Any]:
        run = service.get_run(run_id)
        if not run:
            raise HTTPException(status_code=404, detail="run not found")
        return {"run": run}

    @app.get("/api/v5/runs/{run_id}/continuation")
    def continuation(run_id: str) -> dict[str, Any]:
        service.get_run(run_id) or _missing_run()
        return {"continuation": service.continuation(run_id)}

    @app.get("/api/v5/runs/{run_id}/understanding")
    def understanding(run_id: str) -> dict[str, Any]:
        service.get_run(run_id) or _missing_run()
        return {"understanding": _latest_payload(service.list_artifacts(run_id), "requirements_analysis")}

    @app.get("/api/v5/runs/{run_id}/solution-graph")
    def solution_graph(run_id: str) -> dict[str, Any]:
        service.get_run(run_id) or _missing_run()
        return {"solution_graph": _latest_payload(service.list_artifacts(run_id), "package_dag")}

    @app.get("/api/v5/runs/{run_id}/agent-runs")
    def agent_runs(run_id: str) -> dict[str, Any]:
        service.get_run(run_id) or _missing_run()
        return {"items": [artifact for artifact in service.list_artifacts(run_id) if artifact["kind"] == "agent_run"]}

    @app.get("/api/v5/runs/{run_id}/patch-sets")
    def patch_sets(run_id: str) -> dict[str, Any]:
        service.get_run(run_id) or _missing_run()
        return {"items": [artifact for artifact in service.list_artifacts(run_id) if artifact["kind"] == "patch_set"]}

    @app.get("/api/v5/runs/{run_id}/agent-contract-report")
    def agent_contract_report(run_id: str) -> dict[str, Any]:
        service.get_run(run_id) or _missing_run()
        return {"report": _latest_payload(service.list_artifacts(run_id), "agent_contract_report")}

    @app.get("/api/v5/runs/{run_id}/patch-transactions")
    def patch_transactions(run_id: str) -> dict[str, Any]:
        service.get_run(run_id) or _missing_run()
        artifacts = service.list_artifacts(run_id)
        return {
            "report": _latest_optional_payload(artifacts, "patch_transaction_report"),
            "items": [artifact for artifact in artifacts if artifact["kind"] == "patch_transaction"],
            "conflicts": [artifact for artifact in artifacts if artifact["kind"] == "integration_conflict"],
        }

    @app.get("/api/v5/runs/{run_id}/test-execution")
    def test_execution(run_id: str) -> dict[str, Any]:
        service.get_run(run_id) or _missing_run()
        return {"report": _latest_payload(service.list_artifacts(run_id), "test_execution_report")}

    @app.get("/api/v5/runs/{run_id}/code-index")
    def code_index(run_id: str) -> dict[str, Any]:
        service.get_run(run_id) or _missing_run()
        return {"index": _latest_payload(service.list_artifacts(run_id), "code_index")}

    @app.get("/api/v5/runs/{run_id}/contract-index")
    def contract_index(run_id: str) -> dict[str, Any]:
        service.get_run(run_id) or _missing_run()
        return {"index": _latest_payload(service.list_artifacts(run_id), "contract_index")}

    @app.get("/api/v5/runs/{run_id}/project-layout")
    def project_layout(run_id: str) -> dict[str, Any]:
        service.get_run(run_id) or _missing_run()
        return {"layout": _latest_payload(service.list_artifacts(run_id), "project_layout")}

    @app.get("/api/v5/runs/{run_id}/dag")
    def dag(run_id: str) -> dict[str, Any]:
        service.get_run(run_id) or _missing_run()
        return {"dag": _latest_payload(service.list_artifacts(run_id), "package_dag")}

    @app.get("/api/v5/runs/{run_id}/code-review")
    def code_review(run_id: str) -> dict[str, Any]:
        service.get_run(run_id) or _missing_run()
        return {"report": _latest_payload(service.list_artifacts(run_id), "code_review_report")}

    @app.get("/api/v5/runs/{run_id}/jobs")
    def jobs(run_id: str) -> dict[str, Any]:
        service.get_run(run_id) or _missing_run()
        return {"items": service.list_jobs(run_id)}

    @app.get("/api/v5/runs/{run_id}/ai-calls")
    def ai_calls(run_id: str) -> dict[str, Any]:
        service.get_run(run_id) or _missing_run()
        return {"items": [artifact for artifact in service.list_artifacts(run_id) if artifact["kind"] == "agent_run"]}

    @app.get("/api/v5/runs/{run_id}/waves")
    def waves(run_id: str) -> dict[str, Any]:
        service.get_run(run_id) or _missing_run()
        return {"items": service.store.list_waves(run_id)}

    @app.get("/api/v5/runs/{run_id}/packages")
    def packages(run_id: str) -> dict[str, Any]:
        service.get_run(run_id) or _missing_run()
        return {"items": service.store.list_work_packages(run_id)}

    @app.get("/api/v5/runs/{run_id}/wave-report")
    def wave_report(run_id: str) -> dict[str, Any]:
        service.get_run(run_id) or _missing_run()
        return {"items": [artifact for artifact in service.list_artifacts(run_id) if artifact["kind"] == "wave_report"]}

    @app.get("/api/v5/runs/{run_id}/quality-report")
    def quality_report(run_id: str) -> dict[str, Any]:
        return {"report": _latest_payload(service.list_artifacts(run_id), "quality_report")}

    @app.get("/api/v5/runs/{run_id}/context-index")
    def context_index(run_id: str) -> dict[str, Any]:
        return {"snapshot": _latest_payload(service.list_artifacts(run_id), "context_snapshot")}

    @app.get("/api/v5/runs/{run_id}/repair-history")
    def repair_history(run_id: str) -> dict[str, Any]:
        service.get_run(run_id) or _missing_run()
        return {"items": [artifact for artifact in service.list_artifacts(run_id) if artifact["kind"] == "repair_report"]}

    @app.get("/api/v5/runs/{run_id}/template-leak-report")
    def template_leak_report(run_id: str) -> dict[str, Any]:
        return {"report": _latest_payload(service.list_artifacts(run_id), "template_leak_report")}

    @app.get("/api/v5/runs/{run_id}/agent-trace")
    def agent_trace(run_id: str) -> dict[str, Any]:
        service.get_run(run_id) or _missing_run()
        return {"items": [artifact for artifact in service.list_artifacts(run_id) if artifact["kind"] == "agent_run"]}

    @app.get("/api/v5/runs/{run_id}/artifacts")
    def artifacts(run_id: str) -> dict[str, Any]:
        service.get_run(run_id) or _missing_run()
        return {"items": service.list_artifacts(run_id)}

    @app.get("/api/v5/runs/{run_id}/release-structure")
    def release_structure(run_id: str) -> dict[str, Any]:
        return {"report": _latest_payload(service.list_artifacts(run_id), "release_structure_report")}

    @app.get("/api/v5/runs/{run_id}/deploy-guide")
    def deploy_guide(run_id: str) -> dict[str, Any]:
        return {"guide": _latest_payload(service.list_artifacts(run_id), "deploy_guide")}

    @app.get("/api/v5/runs/{run_id}/browser-smoke")
    def browser_smoke(run_id: str) -> dict[str, Any]:
        return {"report": _latest_payload(service.list_artifacts(run_id), "test_report")}

    @app.post("/api/v5/runs/{run_id}/pause")
    def pause(run_id: str) -> dict[str, Any]:
        service.get_run(run_id) or _missing_run()
        return {"run": service.pause_run(run_id)}

    @app.post("/api/v5/runs/{run_id}/resume")
    def resume(run_id: str) -> dict[str, Any]:
        service.get_run(run_id) or _missing_run()
        return {"run": service.resume_run(run_id)}

    @app.post("/api/v5/runs/{run_id}/requeue-blocked")
    def requeue_blocked(run_id: str) -> dict[str, Any]:
        run = service.get_run(run_id) or _missing_run()
        continuation = dict(run.get("continuation") or {})
        continuation.update({"failure_reason": "", "next_action": "claim_pending_jobs"})
        return {"run": service.store.update_run(run_id, status="queued", continuation=continuation)}

    @app.post("/api/v5/runs/{run_id}/repair")
    def repair(run_id: str) -> dict[str, Any]:
        run = service.get_run(run_id) or _missing_run()
        project = service.get_project(run["project_id"])
        if not project:
            raise HTTPException(status_code=404, detail="project not found")
        return {"job": service._enqueue_repair_job(project, run, "manual_repair", {"source": "api"})}

    @app.post("/api/v5/runs/{run_id}/cancel")
    def cancel(run_id: str) -> dict[str, Any]:
        service.get_run(run_id) or _missing_run()
        return {"run": service.cancel_run(run_id)}

    @app.post("/api/v5/runs/{run_id}/export-delivery")
    def export_delivery(run_id: str, payload: DeliveryExportRequest) -> dict[str, Any]:
        service.get_run(run_id) or _missing_run()
        try:
            report = service.export_delivery(run_id, payload.target_path, overwrite=payload.overwrite)
        except DeliveryExportError as exc:
            raise HTTPException(status_code=400, detail=str(exc))
        return {"ok": True, "report": report}

    @app.get("/api/v5/workers")
    def workers(limit: int = 12) -> dict[str, Any]:
        limit = max(1, min(limit, 100))
        return {"items": WorkerStatusRegistry(service.workspace_root).list(limit=limit), "limit": limit}

    @app.get("/api/v5/dead-letter")
    def dead_letter() -> dict[str, Any]:
        return {"items": service.store.list_jobs(status="dead_letter")}

    @app.post("/api/v5/dead-letter/{job_id}/requeue")
    def requeue_dead_letter(job_id: str) -> dict[str, Any]:
        jobs = [job for job in service.store.list_jobs(status="dead_letter") if job["id"] == job_id]
        if not jobs:
            raise HTTPException(status_code=404, detail="dead-letter job not found")
        job = jobs[0]
        requeued = service.store.enqueue_job(
            job["tenant_id"],
            {
                **job,
                "id": new_id(),
                "status": "queued",
                "attempts": 0,
                "worker_id": "",
                "lease_until": None,
                "heartbeat_at": None,
                "last_error": "",
                "resume_key": f"{job['resume_key']}:manual:{new_id()}",
            },
        )
        if job.get("run_id"):
            run = service.get_run(job["run_id"])
            if run:
                continuation = dict(run.get("continuation") or {})
                continuation.update({"failure_reason": "", "next_action": "claim_pending_jobs"})
                service.store.update_run(job["run_id"], status="queued", continuation=continuation)
        return {"ok": True, "job_id": job_id, "requeued_job_id": requeued["id"]}

    @app.post("/api/v5/release-candidates/{candidate_id}/apply")
    def apply(candidate_id: str) -> dict[str, Any]:
        return {"job": service.enqueue_apply(candidate_id)}

    @app.post("/api/v5/release-candidates/{candidate_id}/rollback")
    def rollback(candidate_id: str) -> dict[str, Any]:
        return {"job": service.enqueue_rollback(candidate_id)}

    for path, endpoint, methods in [
        ("/api/v5/health", health, ["GET"]),
        ("/api/v5/system-check", system_check, ["GET"]),
        ("/api/v5/stack-packs", stack_packs, ["GET"]),
        ("/api/v5/ai-policy", ai_policy, ["GET"]),
        ("/api/v5/model-settings", get_model_settings, ["GET"]),
        ("/api/v5/model-settings", update_model_settings, ["PUT"]),
        ("/api/v5/model-settings/test", test_model_settings, ["POST"]),
        ("/api/v5/projects", create_project, ["POST"]),
        ("/api/v5/projects", list_projects, ["GET"]),
        ("/api/v5/projects/{project_id}", get_project, ["GET"]),
        ("/api/v5/projects/{project_id}/runs", list_project_runs, ["GET"]),
        ("/api/v5/projects/{project_id}", delete_project, ["DELETE"]),
        ("/api/v5/projects/batch-delete", batch_delete_projects, ["POST"]),
        ("/api/v5/projects/{project_id}/requirements", update_requirements, ["POST"]),
        ("/api/v5/projects/{project_id}/stack-decision", stack_decision, ["GET"]),
        ("/api/v5/projects/{project_id}/runs", create_run, ["POST"]),
        ("/api/v5/runs/{run_id}", get_run, ["GET"]),
        ("/api/v5/runs/{run_id}/continuation", continuation, ["GET"]),
        ("/api/v5/runs/{run_id}/understanding", understanding, ["GET"]),
        ("/api/v5/runs/{run_id}/solution-graph", solution_graph, ["GET"]),
        ("/api/v5/runs/{run_id}/agent-runs", agent_runs, ["GET"]),
        ("/api/v5/runs/{run_id}/patch-sets", patch_sets, ["GET"]),
        ("/api/v5/runs/{run_id}/agent-contract-report", agent_contract_report, ["GET"]),
        ("/api/v5/runs/{run_id}/patch-transactions", patch_transactions, ["GET"]),
        ("/api/v5/runs/{run_id}/test-execution", test_execution, ["GET"]),
        ("/api/v5/runs/{run_id}/code-index", code_index, ["GET"]),
        ("/api/v5/runs/{run_id}/contract-index", contract_index, ["GET"]),
        ("/api/v5/runs/{run_id}/project-layout", project_layout, ["GET"]),
        ("/api/v5/runs/{run_id}/dag", dag, ["GET"]),
        ("/api/v5/runs/{run_id}/code-review", code_review, ["GET"]),
        ("/api/v5/runs/{run_id}/jobs", jobs, ["GET"]),
        ("/api/v5/runs/{run_id}/ai-calls", ai_calls, ["GET"]),
        ("/api/v5/runs/{run_id}/waves", waves, ["GET"]),
        ("/api/v5/runs/{run_id}/packages", packages, ["GET"]),
        ("/api/v5/runs/{run_id}/wave-report", wave_report, ["GET"]),
        ("/api/v5/runs/{run_id}/quality-report", quality_report, ["GET"]),
        ("/api/v5/runs/{run_id}/context-index", context_index, ["GET"]),
        ("/api/v5/runs/{run_id}/repair-history", repair_history, ["GET"]),
        ("/api/v5/runs/{run_id}/template-leak-report", template_leak_report, ["GET"]),
        ("/api/v5/runs/{run_id}/agent-trace", agent_trace, ["GET"]),
        ("/api/v5/runs/{run_id}/artifacts", artifacts, ["GET"]),
        ("/api/v5/runs/{run_id}/release-structure", release_structure, ["GET"]),
        ("/api/v5/runs/{run_id}/deploy-guide", deploy_guide, ["GET"]),
        ("/api/v5/runs/{run_id}/browser-smoke", browser_smoke, ["GET"]),
        ("/api/v5/runs/{run_id}/pause", pause, ["POST"]),
        ("/api/v5/runs/{run_id}/resume", resume, ["POST"]),
        ("/api/v5/runs/{run_id}/requeue-blocked", requeue_blocked, ["POST"]),
        ("/api/v5/runs/{run_id}/repair", repair, ["POST"]),
        ("/api/v5/runs/{run_id}/cancel", cancel, ["POST"]),
        ("/api/v5/runs/{run_id}/export-delivery", export_delivery, ["POST"]),
        ("/api/v5/workers", workers, ["GET"]),
        ("/api/v5/dead-letter", dead_letter, ["GET"]),
        ("/api/v5/dead-letter/{job_id}/requeue", requeue_dead_letter, ["POST"]),
        ("/api/v5/release-candidates/{candidate_id}/apply", apply, ["POST"]),
        ("/api/v5/release-candidates/{candidate_id}/rollback", rollback, ["POST"]),
    ]:
        app.add_api_route(path, endpoint, methods=methods, include_in_schema=False)

    return app


def _missing_run() -> None:
    raise HTTPException(status_code=404, detail="run not found")


def _normalize_model_settings_payload(payload: dict[str, Any]) -> dict[str, Any]:
    llm_payload = dict(payload.get("llm") or {})
    provider_key = str(payload.get("model_provider") or "").strip()
    providers = payload.get("model_providers") or {}
    provider = providers.get(provider_key) if isinstance(providers, dict) and provider_key else {}
    if not isinstance(provider, dict):
        provider = {}

    provider_name = str(provider.get("name") or provider_key or "").strip()
    wire_api = str(provider.get("wire_api") or llm_payload.get("wire_api") or "").strip()
    base_url = str(provider.get("base_url") or llm_payload.get("api_base") or "").strip()
    requires_openai_auth = provider.get("requires_openai_auth")

    if provider_name == "custom":
        llm_payload["provider_profile"] = "custom-responses-compatible" if wire_api == "responses" else "custom-chat-compatible"
    elif provider_name:
        llm_payload["provider_profile"] = provider_name
    if base_url:
        llm_payload["api_base"] = base_url
    if wire_api:
        llm_payload["wire_api"] = wire_api
    if payload.get("model"):
        llm_payload["model"] = payload["model"]
    if payload.get("model_reasoning_effort"):
        llm_payload["model_reasoning_effort"] = payload["model_reasoning_effort"]
    if payload.get("disable_response_storage") is not None:
        llm_payload["disable_response_storage"] = bool(payload["disable_response_storage"])
    if payload.get("api_key") not in {"", "***", None}:
        llm_payload["api_key"] = payload["api_key"]
    if requires_openai_auth is True:
        llm_payload.setdefault("auth_header", "Authorization")
        llm_payload.setdefault("auth_scheme", "Bearer")
    if wire_api == "responses":
        llm_payload["api_path"] = str(provider.get("api_path") or "/responses")
        llm_payload["supports_responses"] = True
        llm_payload["supports_chat_completions"] = False
    elif wire_api:
        llm_payload["api_path"] = str(provider.get("api_path") or "/chat/completions")
        llm_payload["supports_responses"] = False
        llm_payload["supports_chat_completions"] = True
    llm_payload["use_mock"] = False
    return llm_payload


def _sync_llm_env_file(root_dir: Path, llm_config: Any) -> None:
    path = root_dir / ".env"
    existing: list[str] = []
    if path.exists():
        try:
            existing = path.read_text(encoding="utf-8").splitlines()
        except OSError:
            existing = []
    updates = {
        "OPENAI_API_BASE": str(getattr(llm_config, "api_base", "") or ""),
        "OPENAI_MODEL": str(getattr(llm_config, "model", "") or ""),
        "OPENAI_WIRE_API": str(getattr(llm_config, "wire_api", "") or ""),
        "OPENAI_PROVIDER_PROFILE": str(getattr(llm_config, "provider_profile", "") or ""),
        "OPENAI_API_PATH": str(getattr(llm_config, "api_path", "") or ""),
        "OPENAI_REASONING_EFFORT": str(getattr(llm_config, "model_reasoning_effort", "") or ""),
        "OPENAI_DISABLE_RESPONSE_STORAGE": "true" if bool(getattr(llm_config, "disable_response_storage", False)) else "false",
    }
    api_key = str(getattr(llm_config, "api_key", "") or "")
    if api_key and api_key != "***":
        updates["OPENAI_API_KEY"] = api_key

    seen: set[str] = set()
    lines: list[str] = []
    for line in existing:
        key = line.split("=", 1)[0].strip() if "=" in line else ""
        if key in updates:
            lines.append(f"{key}={updates[key]}")
            seen.add(key)
        else:
            lines.append(line)
    for key, value in updates.items():
        if key not in seen:
            lines.append(f"{key}={value}")
    path.write_text("\n".join(lines).rstrip() + "\n", encoding="utf-8")


def _latest_payload(artifacts: list[dict[str, Any]], kind: str) -> dict[str, Any]:
    matches = [artifact for artifact in artifacts if artifact["kind"] == kind]
    if not matches:
        raise HTTPException(status_code=404, detail=f"{kind} not found")
    return matches[-1].get("payload") or {}


def _latest_optional_payload(artifacts: list[dict[str, Any]], kind: str) -> dict[str, Any]:
    matches = [artifact for artifact in artifacts if artifact["kind"] == kind]
    return (matches[-1].get("payload") if matches else {}) or {}


def run_api_server(service: V5Orchestrator, config: AppConfig, host: str, port: int) -> None:
    import uvicorn

    uvicorn.run(build_app(service, config), host=host, port=port)

