FROM docker.1ms.run/library/python:3.12-slim

WORKDIR /app

COPY requirements-v5.txt /app/requirements-v5.txt
RUN pip install --no-cache-dir -r requirements-v5.txt

COPY . /app

CMD ["python", "run_server.py", "--api", "--host", "0.0.0.0", "--port", "8787"]
