import {useEffect,useState} from 'react';
import {useRouter} from 'next/router';
const seed={ps:[{id:'P001',n:'螺丝',s:'M8',u:'盒',q:5,l:10},{id:'P002',n:'垫片',s:'10mm',u:'包',q:40,l:20}],logs:[]};
export default function A(){const r=useRouter();const [t,st]=useState('dashboard');const [db,sdb]=useState(seed);const [msg,sm]=useState('');const [kw,sk]=useState('');const [low,sl]=useState(false);const [pg,sp]=useState(1);const [f,sf]=useState({n:'',s:'',u:'件',l:0});const [io,sio]=useState({id:'P001',q:1,remark:'',date:new Date().toISOString().slice(0,10)});const [pw,spw]=useState({o:'',n:'',c:''});
 useEffect(()=>{if(!sessionStorage.getItem('auth'))r.replace('/')},[]); const save=v=>sdb({...v}); const lowList=db.ps.filter(x=>x.q<x.l), list=db.ps.filter(x=>x.n.includes(kw)||x.id.includes(kw)).filter(x=>!low||x.q<x.l), size=5, show=list.slice((pg-1)*size,pg*size);
 const add=()=>{if(!f.n)return sm('请填写产品名称'); save({ ...db, ps:[...db.ps,{id:'P'+Date.now().toString().slice(-4),...f,q:0,l:+f.l}]}); sf({n:'',s:'',u:'件',l:0}); sm('新增成功')};
 const del=id=>window.confirm('确认删除该产品吗？')&&(save({...db,ps:db.ps.filter(x=>x.id!==id)}),sm('删除成功'));
 const move=type=>{const i=db.ps.findIndex(x=>x.id===io.id), p=db.ps[i], q=+io.q; if(!p||q<=0)return sm('数量无效'); if(type==='出库'&&p.q<q)return sm('库存不足，当前库存为 '+p.q); const ps=[...db.ps]; ps[i]={...p,q:type==='入库'?p.q+q:p.q-q}; save({...db,ps,logs:[{...io,type,p:p.n},...db.logs]}); sm(type+'成功')};
 const cp=()=>{const cur=sessionStorage.getItem('pwd')||'admin'; if(pw.o!==cur)return sm('原密码错误'); if(!pw.n||pw.n!==pw.c)return sm('两次新密码不一致'); sessionStorage.setItem('pwd',pw.n); sm('密码修改成功')};
 const out=()=>{sessionStorage.clear();r.push('/')};
 return <div style={{padding:20,fontFamily:'sans-serif'}}><div style={{display:'flex',gap:8,flexWrap:'wrap'}}>{['dashboard:仪表盘','product:产品管理','in:入库管理','out:出库管理','stock:库存查询','log:出入库记录','pwd:密码修改'].map(x=>{const[a,b]=x.split(':');return <button key={a} onClick={()=>st(a)}>{b}</button>})}<button onClick={out}>退出登录</button></div>{msg&&<p style={{color:msg.includes('成功')?'green':'red'}}>{msg}</p>}
 {t==='dashboard'&&<div><h3>仪表盘</h3><p>产品总数：{db.ps.length}　库存总数：{db.ps.reduce((a,b)=>a+b.q,0)}　低库存数：{lowList.length}</p><p>警告：以下产品库存不足</p><ul>{lowList.map(x=><li key={x.id}>{x.n}（{x.q}/{x.l}） <a href='#' onClick={e=>(e.preventDefault(),st('in'))}>去入库</a></li>)}</ul></div>}
 {t==='product'&&<div><h3>产品管理</h3><input placeholder='搜索' value={kw} onChange={e=>sk(e.target.value)}/> <button>搜索</button><div>产品名称<input value={f.n} onChange={e=>sf({...f,n:e.target.value})}/> 规格型号<input value={f.s} onChange={e=>sf({...f,s:e.target.value})}/> 单位<input value={f.u} onChange={e=>sf({...f,u:e.target.value})}/> 最低库存警戒<input type='number' value={f.l} onChange={e=>sf({...f,l:e.target.value})}/><button onClick={add}>新增</button></div><table border='1' cellPadding='6'><thead><tr><th>产品编号</th><th>产品名称</th><th>规格型号</th><th>单位</th><th>当前库存</th><th>最低库存警戒</th><th>操作</th></tr></thead><tbody>{show.map(x=><tr key={x.id}><td>{x.id}</td><td>{x.n}</td><td>{x.s}</td><td>{x.u}</td><td>{x.q}</td><td>{x.l}</td><td><button onClick={()=>del(x.id)}>删除</button></td></tr>)}</tbody></table><button disabled={pg===1} onClick={()=>sp(pg-1)}>上一页</button><button disabled={pg*size>=list.length} onClick={()=>sp(pg+1)}>下一页</button></div>}
 {['in','out'].includes(t)&&<div><h3>{t==='in'?'入库管理':'出库管理'}</h3><select value={io.id} onChange={e=>sio({...io,id:e.target.value})}>{db.ps.map(x=><option key={x.id} value={x.id}>{x.n}</option>)}</select><input type='number' value={io.q} onChange={e=>sio({...io,q:e.target.value})}/><input placeholder='备注' value={io.remark} onChange={e=>sio({...io,remark:e.target.value})}/><input type='date' value={io.date} onChange={e=>sio({...io,date:e.target.value})}/><button onClick={()=>move(t==='in'?'入库':'出库')}>{t==='in'?'确认入库':'确认出库'}</button><ul>{db.logs.filter(x=>x.type===(t==='in'?'入库':'出库')).slice(0,5).map((x,i)=><li key={i}>{x.date} {x.p} {x.q} {x.remark}</li>)}</ul></div>}
 {t==='stock'&&<div><h3>库存查询</h3><label><input type='checkbox' checked={low} onChange={e=>sl(e.target.checked)}/>仅显示库存不足产品</label><table border='1' cellPadding='6'><thead><tr><th>产品名称</th><th>规格型号</th><th>单位</th><th>当前库存</th><th>最低库存警戒</th><th>状态</th></tr></thead><tbody>{list.map(x=><tr key={x.id}><td>{x.n}</td><td>{x.s}</td><td>{x.u}</td><td>{x.q}</td><td>{x.l}</td><td>{x.q<x.l?'库存不足':'正常'}</td></tr>)}</tbody></table></div>}
 {t==='log'&&<div><h3>出入库记录</h3><table border='1' cellPadding='6'><thead><tr><th>日期</th><th>类型</th><th>产品</th><th>数量</th><th>备注</th></tr></thead><tbody>{db.logs.slice((pg-1)*size,pg*size).map((x,i)=><tr key={i}><td>{x.date}</td><td>{x.type}</td><td>{x.p}</td><td>{x.q}</td><td>{x.remark}</td></tr>)}</tbody></table><button disabled={pg===1} onClick={()=>sp(pg-1)}>上一页</button><button disabled={pg*size>=db.logs.length} onClick={()=>sp(pg+1)}>下一页</button></div>}
 {t==='pwd'&&<div><h3>密码修改</h3><div>原密码<input type='password' value={pw.o} onChange={e=>spw({...pw,o:e.target.value})}/></div><div>新密码<input type='password' value={pw.n} onChange={e=>spw({...pw,n:e.target.value})}/></div><div>确认新密码<input type='password' value={pw.c} onChange={e=>spw({...pw,c:e.target.value})}/></div><button onClick={cp}>确认修改</button></div>}</div>}
