const express=require('express');
const session=require('express-session');
const multer=require('multer');
const path=require('path');
const fs=require('fs');
const auth=require('../middleware/auth');
const s=require('../services/blogStore');
const r=express.Router();
fs.mkdirSync('uploads',{recursive:true});
const up=multer({dest:'uploads/'});
r.use(session({secret:'blog-secret',resave:false,saveUninitialized:false}));
r.use('/uploads',express.static(path.resolve('uploads')));
r.post('/auth/login',(req,res)=>{const {username,password}=req.body||{};if(username===s.db.admin.username&&password===s.db.admin.password){req.session.admin={username};return res.json({message:'登录成功'});}res.status(400).json({message:'用户名或密码错误'});});
r.post('/auth/logout',auth,(req,res)=>req.session.destroy(()=>res.json({message:'已退出'})));
r.get('/auth/me',(req,res)=>res.json({loggedIn:!!(req.session&&req.session.admin)}));
r.get('/categories',(req,res)=>res.json(s.listCat()));
r.post('/categories',auth,(req,res)=>res.json(s.addCat(req.body||{})));
r.put('/categories/:id',auth,(req,res)=>res.json(s.updCat(req.params.id,req.body||{})));
r.delete('/categories/:id',auth,(req,res)=>{s.delCat(req.params.id);res.json({message:'已删除'});});
r.get('/articles',(req,res)=>res.json(s.listArt({page:+req.query.page||1,pageSize:15,q:req.query.q||'',categoryId:req.query.categoryId,deleted:req.query.deleted==null?undefined:req.query.deleted==='true'})));
r.post('/articles',auth,(req,res)=>res.json(s.addArt(req.body||{})));
r.put('/articles/:id',auth,(req,res)=>res.json(s.updArt(req.params.id,req.body||{})));
r.delete('/articles/:id',auth,(req,res)=>res.json(s.setDel(req.params.id,true)||{}));
r.post('/articles/:id/restore',auth,(req,res)=>res.json(s.setDel(req.params.id,false)||{}));
r.get('/articles/:id',(req,res)=>{const a=s.getArt(req.params.id,true);if(!a)return res.status(404).json({message:'未找到'});res.json({...a,html:s.render(a.content)});});
r.post('/render/markdown',(req,res)=>res.json({html:s.render((req.body||{}).content)}));
r.post('/upload',auth,up.single('image'),(req,res)=>{if(!req.file)return res.status(400).json({message:'缺少图片'});res.json({url:`/uploads/${req.file.filename}`,markdown:`![](/uploads/${req.file.filename})`});});
module.exports=r;
